### ISSUE TITLE
fix log_add logic

### ISSUE THREAD

**Issue by mayankc** [brianhempel/demarcken_word_segmentation#1]
At some point this used to be 
> a_i += alphas[j] * word_probability

now it has changed to 
> a_i = a_i+log(1+2^word_probability/2^a_i)) ~(word_probability)

does not seem correct

https://github.com/brianhempel/demarcken_word_segmentation/blob/44a3096c80dd6278574e888f10c6e3f5df3e654e/word_segmenter.py#L87

**Comment by brianhempel** [comment]
Probabilities are numbers between 0 and 1. When you multiply a bunch of probabilities together, the numbers get really small and floating point math underflows, rounding to zero. To avoid this problem, you work with the log of probability instead. Multiplication becomes addition. Addition becomes the mess you see.

**Comment by mayankc** [comment]
thanks for the prompt response @brianhempel . i understand the need to work with log probabilities.  

My questions is around the calculations . 
seems like you are updating a_i to approx(word_probability) at each step instead of adding it to a_i.

the calling function is used like this -

> a_i = log_add(a_i,term)

The previous formula , though it was casing underflows, was correct

**Comment by brianhempel** [comment]
The multiplication was moved to the prior line:

https://github.com/brianhempel/demarcken_word_segmentation/blob/44a3096c80dd6278574e888f10c6e3f5df3e654e/word_segmenter.py#L119

**Comment by mayankc** [comment]
correct, so shouldn't log_add be 

> return x+log(1+2**(y)) 

and not 

> return x+log(1+2**(y-x)) 

assuming here that x and y are both base2 logs. 
we need to be adding up all the 'term' probabilities at this step.

 or you can change the calling function to -

> a_i += log_add(a_i,term)

**Comment by brianhempel** [comment]
log is logarithm base 2
x = log(a)
y = log(b)
log(a + b) = [log(a) + log( 1 + b/a )](https://en.wikipedia.org/wiki/List_of_logarithmic_identities#Summation/subtraction)
log(a + b) = log(a) + log( 1 + (2^log(b))/(2^log(a)) )
log(a + b) = log(a) + log( 1 + 2^(log(b) - log(a)) )
log(a + b) = x + log( 1 + 2^(y - x) )

**Comment by mayankc** [comment]
got it, i was missing the part that you are taking logs after the addition.

thank you so much for taking the time to document and explain this.
💯
